### ISSUE TITLE
ready?

### ISSUE THREAD

**Issue by JeffreyDavidsz** [bitfocus/companion-module-avstumpfl-pixera#1]
@BenniMTools let me know when you are ready

**Comment by BenniMTools** [comment]
I'm ready. Thanks :-)

**Comment by JeffreyDavidsz** [comment]
@BenniMTools please check your identation settings, use tabwitdh=2 (no spaces). If edited the module for now.

**Comment by BenniMTools** [comment]
@JeffreyDavidsz sorry i will check that
