### ISSUE TITLE
Tested Pixera module, found some bugs

### ISSUE THREAD

**Issue by wvanmaris** [bitfocus/companion-module-avstumpfl-pixera#3]
So, tested the Pixera module from version 

- Transport functions and Goto Cue / Goto Timecode work fine.
- Blend to Cue doesn't seem to work, whatever I try. 
- Blend to Timecode also doesn't work.
- Goto Cue index works, but, on Pixera forum I read that Timeline 1 would be timeline index 0.  But in fact, it's just index 1. (perhaps I've misread.
-Next/Prev Cue work fine
- Ingore next cue works fine
- Newly created timelines seem to require a full restart of Companion core to be recognised (where Pixera stays active). Refresh Browser (F5 / Shift F5 dont work). 
Alternatively, a restart of Pixera (where in turn Companion stays active) also shows the new timeline.  So either way, one of the two programs seem to need a restart.

- Visible screen / Projectable  = I get no feedback from Pixera to choose from. Am I missing something?
- Timeline Store = what is that supposed to do?

**Comment by BenniMTools** [comment]
Hi wvanmaris,

thanks for reply.
Blend to Cue and Blend to Timecode is only available in the beta and will be hopefully announced with the next released.

if you create a new timeline you have to reconnect to pixera to get these. just disconnect and connect again.
next week i'm in office and will try to do it automatically but it's a lot of network traffic :-(.

visible screen/projectable. did you create a screen in pixera? i will check that next week.

timeline store is a shortkey to store active values to the timeline. (there is a bug in Pixera that Opacity are not stored by API call)

**Comment by wvanmaris** [comment]
Thanks so much for your reply!! 
Sounds clear! 


Walter van Maris


Mobiel verstuurd
