### ISSUE TITLE
Latest Companion & Pixera Still Having Blend to Cue Issues

### ISSUE THREAD

**Issue by btb44333** [bitfocus/companion-module-avstumpfl-pixera#6]
Blend to Cue seems to work very irregularly - meaning not going to the named Cue at all -  and even when it does,  it seems it probably isn't blending,  or the Cue to which it moves might not fire (i.e., the Pointer might move to the Cue but the Play function of the Cue doesn't fire).

Any chance you have some insight?  This has happened to me on my current (using AVStumpfl 4 Quads) and previous (using custom builds with dongles) shows.

**Comment by kylemeans** [comment]
Yeah I'm seeing the same thing here. Would love for this to work!

**Comment by btb44333** [comment]
I wonder if these things all now fall under "wait until 2.0..."
-------- Original message --------From: kylemeans ***@***.***> Date: 9/29/23  3:07 PM  (GMT-05:00) To: bitfocus/companion-module-avstumpfl-pixera ***@***.***> Cc: btb44333 ***@***.***>, Author ***@***.***> Subject: Re: [bitfocus/companion-module-avstumpfl-pixera] Latest Companion & Pixera Still Having Blend to Cue Issues (Issue #6) 
Yeah I'm seeing the same thing here. Would love for this to work!

**Comment by BenniMTools** [comment]
the poblem is that this functions exists before the api call in pixera exists.
currently the function is getting the cue time and makes a bled to time. thats why the cue is not called.

we will check that and update companion
